Project 7 - E-Commerce Platform/shuup/admin/urls.py
 

from __future__ import unicode_literals

import warnings
from django.conf.urls import url
from django.contrib.auth import logout as do_logout
from django.views.decorators.csrf import csrf_exempt
from django.views.i18n import set_language

from shuup.admin.module_registry import get_module_urls
from shuup.admin.utils.urls import AdminRegexURLPattern, admin_url
from shuup.admin.views.auth import LoginView, LogoutView
from shuup.admin.views.dashboard import DashboardView
from shuup.admin.views.edit import EditObjectView
from shuup.admin.views.home import HomeView
from shuup.admin.views.impersonate import stop_impersonating_staff
from shuup.admin.views.menu import MenuToggleView, MenuView
from shuup.admin.views.password import RequestPasswordView, ResetPasswordView
from shuup.admin.views.search import SearchView
from shuup.admin.views.select import MultiselectAjaxView, ObjectSelectorView
from shuup.admin.views.tour import TourView
from shuup.admin.views.wizard import WizardView
from shuup.utils.django_compat import is_anonymous
from shuup.utils.i18n import javascript_catalog_all


def login(request, **kwargs):
    if not is_anonymous(request.user) and request.method == "POST":  # We're logging in, so log out first
        do_logout(request)

    kwargs.setdefault("extra_context", {})["error"] = request.GET.get("error")
    return LoginView.as_view(**kwargs)(request)


def get_urls():
    urls = []
    urls.extend(get_module_urls())

    urls.extend(
        [
            admin_url(r"^$", DashboardView.as_view(), name="dashboard", permissions=()),
            admin_url(r"^home/$", HomeView.as_view(), name="home", permissions=()),
            admin_url(r"^wizard/$", WizardView.as_view(), name="wizard", permissions=()),
            admin_url(r"^tour/$", TourView.as_view(), name="tour", permissions=()),
            admin_url(r"^search/$", SearchView.as_view(), name="search", permissions=()),
            admin_url(r"^select/$", MultiselectAjaxView.as_view(), name="select", permissions=()),
            admin_url(r"^object-selector/$", ObjectSelectorView.as_view(), name="object_selector", permissions=()),
            admin_url(r"^edit/$", EditObjectView.as_view(), name="edit", permissions=()),
            admin_url(r"^menu/$", MenuView.as_view(), name="menu", permissions=()),
            admin_url(r"^toggle-menu/$", MenuToggleView.as_view(), name="menu_toggle", permissions=()),
            admin_url(
                r"^stop-impersonating-staff/$",
                stop_impersonating_staff,
                name="stop-impersonating-staff",
                permissions=(),
            ),
            admin_url(
                r"^login/$",
                login,
                kwargs={"template_name": "shuup/admin/auth/login.jinja"},
                name="login",
                require_authentication=False,
                permissions=(),
            ),
            admin_url(r"^logout/$", LogoutView, name="logout", require_authentication=False, permissions=()),
            admin_url(
                r"^recover-password/(?P<uidb64>.+)/(?P<token>.+)/$",
                ResetPasswordView,
                name="recover_password",
                require_authentication=False,
                permissions=(),
            ),
            admin_url(
                r"^request-password/$",
                RequestPasswordView,
                name="request_password",
                require_authentication=False,
                permissions=(),
            ),
            admin_url(r"^set-language/$", csrf_exempt(set_language), name="set-language", permissions=()),
        ]
    )

    for u in urls:  # pragma: no cover
        if not isinstance(u, AdminRegexURLPattern):
            warnings.warn("Warning! Admin URL %r is not an `AdminRegexURLPattern`." % u)

    # Add Django javascript catalog url
    urls.append(url(r"^i18n.js$", javascript_catalog_all, name="js-catalog"))

    return tuple(urls)


app_name = "shuup_admin"
urlpatterns = get_urls()

Project 7 - E-Commerce Platform/shuup/admin/modules/orders/views/addresses.py
 
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import UpdateView

from shuup.admin.toolbar import PostActionButton, Toolbar
from shuup.admin.utils.urls import get_model_url
from shuup.core.models import Order, Shop
from shuup.utils.analog import LogEntryKind
from shuup.utils.form_group import FormGroup
from shuup.utils.importing import cached_load
from shuup.utils.models import get_data_dict

ADDRESS_EDITED_LOG_IDENTIFIER = "order-address-edited"


class OrderAddressEditView(UpdateView):
    model = Order
    context_object_name = "order"
    template_name = "shuup/admin/orders/_address_edit.jinja"

    def get_queryset(self):
        shop_ids = Shop.objects.get_for_user(self.request.user).values_list("id", flat=True)
        return Order.objects.exclude(deleted=True).filter(shop_id__in=shop_ids)

    def get_form(self, form_class=None):
        order = self.get_object()
        form_group = FormGroup(**self.get_form_kwargs())
        address_form_class = cached_load("SHUUP_ADDRESS_MODEL_FORM")
        form_group.add_form_def(
            "billing_address",
            address_form_class,
            kwargs={"initial": get_data_dict(order.billing_address) if order.billing_address else {}},
        )
        form_group.add_form_def(
            "shipping_address",
            address_form_class,
            kwargs={"initial": get_data_dict(order.shipping_address) if order.shipping_address else {}},
        )
        return form_group

    def form_valid(self, form):
        order = self.get_object()
        for key, field_title in [
            ("billing_address", _("Billing Address")),
            ("shipping_address", _("Shipping Address")),
        ]:
            if not form[key].has_changed():
                continue
            new_mutable_address = form[key].save()
            new_immutable_address = new_mutable_address.to_immutable()
            new_immutable_address.save()
            old_address = getattr(order, key)
            setattr(order, key, new_immutable_address)
            new_mutable_address.delete()
            order.save(update_fields=[key])
            log_entry_message = _("%(field)s updated from: %(old_address)s") % {
                "field": field_title,
                "old_address": old_address,
            }
            order.add_log_entry(
                log_entry_message[:256], identifier=ADDRESS_EDITED_LOG_IDENTIFIER, kind=LogEntryKind.EDIT
            )
            messages.success(self.request, _("%(field)s were saved.") % {"field": field_title})

        return HttpResponseRedirect(get_model_url(order))

    def get_form_kwargs(self):
        kwargs = super(OrderAddressEditView, self).get_form_kwargs()
        kwargs.pop("instance")
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(OrderAddressEditView, self).get_context_data(**kwargs)
        context["title"] = _("Save -- %s") % context["order"]
        context["toolbar"] = Toolbar(
            [
                PostActionButton(
                    icon="fa fa-check-circle",
                    form_id="edit-addresses",
                    text=_("Save"),
                    extra_css_class="btn-primary",
                ),
            ],
            view=self,
        )
        return context

Project 7 - E-Commerce Platform/shuup/admin/modules/orders/views/refund.py
 
from django import forms
from django.conf import settings
from django.contrib import messages
from django.http.response import HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.views.generic import UpdateView

from shuup.admin.supplier_provider import get_supplier
from shuup.admin.toolbar import PostActionButton, Toolbar, URLActionButton
from shuup.admin.utils.urls import get_model_url
from shuup.core.excs import InvalidRefundAmountException, NoRefundToCreateException, RefundExceedsAmountException
from shuup.core.models import Order, OrderLineType, Shop
from shuup.utils.django_compat import reverse
from shuup.utils.money import Money


class RefundForm(forms.Form):
    line_number = forms.ChoiceField(
        label=_("Line"),
        required=False,
        help_text=_(
            "The line to refund. " "To refund an amount not associated with any line, select 'Refund arbitrary amount'."
        ),
    )
    quantity = forms.DecimalField(
        required=False, min_value=0, initial=0, label=_("Quantity"), help_text=_("The number of units to refund.")
    )
    text = forms.CharField(
        max_length=255,
        label=_("Line Text/Comment"),
        required=False,
        help_text=_("The text describing the nature of the refund and/or the reason for the refund."),
    )
    amount = forms.DecimalField(
        required=False, initial=0, label=_("Amount"), help_text=_("The amount including tax to refund.")
    )
    restock_products = forms.BooleanField(
        required=False,
        initial=True,
        label=_("Restock products"),
        help_text=_("If checked, the quantity is adding back into the sellable product inventory."),
    )

    def clean_line_number(self):
        line_number = self.cleaned_data["line_number"]
        return line_number if line_number != "" else None

    def clean_quantity(self):
        quantity = self.cleaned_data["quantity"]
        return quantity if quantity != 0 else None

    def clean_amount(self):
        amount = self.cleaned_data["amount"]
        return amount if amount != 0 else None


class OrderCreateRefundView(UpdateView):
    model = Order
    template_name = "shuup/admin/orders/create_refund.jinja"
    context_object_name = "order"
    form_class = forms.formset_factory(RefundForm, extra=1)

    def get_queryset(self):
        shop_ids = Shop.objects.get_for_user(self.request.user).values_list("id", flat=True)
        return Order.objects.exclude(deleted=True).filter(shop_id__in=shop_ids)

    def get_context_data(self, **kwargs):
        context = super(OrderCreateRefundView, self).get_context_data(**kwargs)
        context["title"] = _("Create Refund -- %s") % context["order"]
        context["toolbar"] = Toolbar(
            [
                PostActionButton(
                    icon="fa fa-check-circle",
                    form_id="create_refund",
                    text=_("Create Refund"),
                    extra_css_class="btn-success",
                )
            ],
            view=self,
        )

        # Allowing full refunds for suppliers would block the refunds for
        # rest of the suppliers since full refund can only be created once
        supplier = context["supplier"] = get_supplier(self.request)
        if not supplier:
            context["toolbar"].append(
                URLActionButton(
                    url=reverse("shuup_admin:order.create-full-refund", kwargs={"pk": self.object.pk}),
                    icon="fa fa-dollar",
                    text=_("Refund Entire Order"),
                    extra_css_class="btn-info",
                    disable_reason=_("This order already has existing refunds") if self.object.has_refunds() else None,
                )
            )

        # Setting the line_numbers choices dynamically creates issues with the blank formset,
        # So adding that to the context to be rendered manually
        context["line_number_choices"] = self._get_line_number_choices(supplier)

        lines = lines = self.object.lines.all()
        if supplier:
            lines = lines.filter(supplier=supplier)
        context["json_line_data"] = {line.ordering: self._get_line_data(self.object, line) for line in lines}
        return context

    def _get_line_data(self, order, line):
        shop = order.shop
        total_price = line.taxful_price.value if shop.prices_include_tax else line.taxless_price.value
        base_data = {
            "id": line.id,
            "type": "other" if line.quantity else "text",
            "text": line.text,
            "quantity": line.quantity - line.refunded_quantity,
            "sku": line.sku,
            "baseUnitPrice": line.base_unit_price.value,
            "unitPrice": total_price / line.quantity if line.quantity else 0,
            "unitPriceIncludesTax": shop.prices_include_tax,
            "amount": line.max_refundable_amount.value,
            "errors": "",
            "step": "",
        }
        if line.product:
            shop_product = line.product.get_shop_instance(shop)
            supplier = line.supplier
            stock_status = supplier.get_stock_status(line.product.pk) if supplier else None
            base_data.update(
                {
                    "type": "product",
                    "product": {"id": line.product.pk, "text": line.product.name},
                    "step": shop_product.purchase_multiple,
                    "logicalCount": stock_status.logical_count if stock_status else 0,
                    "physicalCount": stock_status.physical_count if stock_status else 0,
                    "salesDecimals": line.product.sales_unit.decimals if line.product.sales_unit else 0,
                    "salesUnit": line.product.sales_unit.symbol if line.product.sales_unit else "",
                }
            )
        return base_data

    def get_form_kwargs(self):
        kwargs = super(OrderCreateRefundView, self).get_form_kwargs()
        kwargs.pop("instance")
        return kwargs

    def _get_line_text(self, line):
        text = "line %s: %s" % (line.ordering + 1, line.text)
        if line.sku:
            text += " (SKU %s)" % (line.sku)
        return text

    def _get_line_number_choices(self, supplier):
        lines = self.object.lines.all()
        if supplier:
            lines = lines.filter(supplier=supplier)

        line_number_choices = [("", "---")]
        if settings.SHUUP_ALLOW_ARBITRARY_REFUNDS and self.object.get_total_unrefunded_amount(supplier).value > 0:
            line_number_choices += [("amount", _("Refund arbitrary amount"))]
        return line_number_choices + [
            (line.ordering, self._get_line_text(line))
            for line in lines
            if (
                (
                    (line.type == OrderLineType.PRODUCT and line.max_refundable_quantity > 0)
                    or (
                        line.type != OrderLineType.PRODUCT
                        and line.max_refundable_amount.value > 0
                        and line.max_refundable_quantity > 0
                    )
                )
                and line.type != OrderLineType.REFUND
            )
        ]

    def get_form(self, form_class=None):
        formset = super(OrderCreateRefundView, self).get_form(form_class)

        # Line orderings are zero-indexed, but shouldn't display that way
        choices = self._get_line_number_choices(get_supplier(self.request))
        for form in formset.forms:
            form.fields["line_number"].choices = choices
        formset.empty_form.fields["line_number"].choices = choices

        return formset

    def _get_refund_line_info(self, order, data, supplier):
        refund_line_info = {}
        amount_value = data.get("amount", 0) or 0
        line_number = data.get("line_number")
        quantity = data.get("quantity", 0) or 1
        restock_products = data.get("restock_products")

        if line_number != "amount":
            lines = order.lines.filter(ordering=line_number)
            if supplier:
                lines = lines.filter(supplier=supplier)

            line = lines.first()

            if not line:
                return None
            refund_line_info["line"] = line
            refund_line_info["quantity"] = quantity
            refund_line_info["restock_products"] = bool(restock_products)
        else:
            refund_line_info["line"] = "amount"
            refund_line_info["text"] = data.get("text")
            refund_line_info["quantity"] = 1
        refund_line_info["amount"] = Money(amount_value, order.currency)
        return refund_line_info

    def form_valid(self, form):
        order = self.object
        supplier = get_supplier(self.request)
        refund_lines = []

        for refund in form.cleaned_data:
            line = self._get_refund_line_info(order, refund, supplier)
            if line:
                refund_lines.append(line)

        try:
            order.create_refund(refund_lines, created_by=self.request.user, supplier=supplier)
        except RefundExceedsAmountException:
            messages.error(self.request, _("Refund amount exceeds order amount."))
            return self.form_invalid(form)
        except InvalidRefundAmountException:
            messages.error(self.request, _("Refund amounts should match sign on parent line."))
            return self.form_invalid(form)
        messages.success(self.request, _("Refund created."))
        return HttpResponseRedirect(get_model_url(order))


class FullRefundConfirmationForm(forms.Form):
    restock_products = forms.BooleanField(required=False, initial=True, label=_("Restock products"))


class OrderCreateFullRefundView(UpdateView):
    model = Order
    template_name = "shuup/admin/orders/create_full_refund.jinja"
    context_object_name = "order"
    form_class = FullRefundConfirmationForm

    def get_queryset(self):

Project 7 - E-Commerce Platform/shuup/admin/templates/shuup/admin/orders/_address_edit.jinja
{% extends "shuup/admin/base.jinja" %}
{% from "shuup/admin/macros/general.jinja" import content_block %}

{% macro address_form(form) %}
    {% for field in form %}
    {{ bs3.field(field) }}
    {% endfor %}
{% endmacro %}

{% block content %}
    <div class="container-fluid">
        <div class="content-block">
            <div class="row">
                <div class="pb-4 col-xl-12">
                    <label>
                        <input id="billing-to-shipping" type="checkbox">
                        {% trans %}Use billing address as shipping address{% endtrans %}
                    </label>
                </div>
            </div>
            <form method="post" action="" id="edit-addresses">
                <div class="row order-addresses">
                    {% csrf_token %}
                    <div class="col-lg-6 billing-address">
                        <h4 class="underline"><i class="fa fa-file-text"></i> {% trans %}Billing Address{% endtrans %}</h4>
                        {{ address_form(form["billing_address"]) }}
                    </div>
                    <div class="col-lg-6 shipping-address">
                        <h4 class="underline"><i class="fa fa-truck"></i> {% trans %}Shipping Address{% endtrans %}</h4>
                        {{ address_form(form["shipping_address"]) }}
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
    $(function(){
        var shouldCopyFields = false;
        function toggleAndCopyFields() {
            shouldCopyFields = $("#billing-to-shipping").is(":checked");
            if (shouldCopyFields) {
                // copy all billing fields values to shipping fields
                $(".billing-address :input").each(function (index, element) {
                    copyFieldValue(this);
                });
            }
            $(".shipping-address :input")
                .attr("readonly", shouldCopyFields)
                .toggleClass("disabled", shouldCopyFields)
                .trigger("change");
            // copy all billing fields values to shipping fields AGAIN
            // this is required when region app is enabled
            // as we can't guarantee the order fields are copied.
            // the region code could be copied before the country and when country
            // is changed, the region code field can be replaced by a select and
            // have options created. this way, we should copy values
            // before the `change` event trigged above and once again after
            // all fields get changed
            if (shouldCopyFields) {
                $(".billing-address :input").each(function (index, element) {
                    copyFieldValue(this);
                });
            }
        }
        function copyFieldValue(element) {
            if(!shouldCopyFields || !element)
                return;
            var targetName = $(element).attr("id").split("-")[1];
            var $target = $("#id_shipping_address-" + targetName);
            $target.val(element.value);
            $target.trigger("change");
        }
        function activateCheckoutAddressCopy() {
            $("#id_shipping-country").attr("readonly", true);
            toggleAndCopyFields();
            $("#billing :input").on("input change", function (evt) {
                copyFieldValue(evt.target);
            });
            $("#billing-to-shipping").on("change", toggleAndCopyFields);
        }
        activateCheckoutAddressCopy();
        // we detectec that a field could be replaced by any other input
        // in cases like regions module is injected
        // this way, we must attach the event again
        document.addEventListener("regionFieldInitialized", function (evt) {
            if ($(evt.detail.field).attr("name").indexOf("billing") >= 0) {
                $(evt.detail.field).on("input change", function (evt) {
                    copyFieldValue(evt.target)
                });
            }
        });
    });
</script>
{% endblock %}

Project 7 - E-Commerce Platform/shuup/admin/templates/shuup/admin/orders/_admin_comment.jinja
<div id="order-admin-comment">
    <form action="" method="post">
        <div class="form-group form-content">
            <label class="control-label" for="admin-comment">{% trans %}Comment{% endtrans %}</label>
            <div class="form-input-group d-flex">
                <textarea class="form-control" id="admin-comment">{{ order.admin_comment }}</textarea>
            </div>
        </div>
        <div class="row">
            <div class="input-actions col-12">
                <button class="btn btn-info" href="#">{% trans %}Save comment{% endtrans %}</button>
            </div>
        </div>
        {% csrf_token %}
    </form>
</div>

Project 7 - E-Commerce Platform/shuup/admin/templates/shuup/admin/orders/_admin_comment_extra_js.jinja
<script>
    (function(){
        $("#order-admin-comment button").on("click", function(event){
            event.preventDefault();
            $.ajax({
                type: "POST",
                url: "{{ url('shuup_admin:order.update-admin-comment', pk=order.pk) }}",
                data: {
                    "comment": $("#admin-comment").val(),
                    "csrfmiddlewaretoken": '{{ csrf_token }}',
                },
                success: function(data){
                    $("#admin-comment").val(data["comment"]);
                    window.Messages.enqueue({tags: "success", text: "{% trans %}Comment was saved.{% endtrans %}"});
                },
                error: function(){
                    alert("{% trans %}Updating the admin comment failed.{% endtrans %}")
                },
            });
        });
    })();
</script>

Project 7 - E-Commerce Platform/shuup/admin/templates/shuup/admin/orders/_detail_payments.jinja
<div class="d-sm-none d-md-block table-responsive">
    <table class="table table-striped {% if not payments %} hidden {% endif %}">
        <thead>
        <tr>
            <th>{% trans %}Date{% endtrans %}</th>
            <th>{% trans %}Identifier{% endtrans %}</th>
            <th>{% trans %}Description{% endtrans %}</th>
            <th class="text-right">{% trans %}Amount{% endtrans %}</th>
            <th>{% trans %}Actions{% endtrans %}</th>
        </tr>
        </thead>
        <tbody>
        {% for payment in payments %}
            <tr>
                <td>{{ payment.created_on|datetime }}</td>
                <td>{{ payment.payment_identifier }}</td>
                <td>{{ payment.description }}</td>
                <td class="text-right">{{ payment.amount|money }}</td>
                <td>
                    {% if not (payment.order.is_complete() or payment.order.is_canceled()) %}
                    <a
                        href="{{ url('shuup_admin:order.delete-payment', pk=payment.order_id) }}"
                        data-payment="{{ payment.pk }}"
                        name="delete-payment-link"
                        class="btn btn-danger btn-sm"
                    >
                        <i class="fa fa-close"></i> {{ _("Delete") }}
                    </a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="d-none d-sm-block d-md-none mobile-list-group {% if not payments %} hidden {% endif %}">
    <ul class="list-group">
        {% for payment in payments %}
            <li class="list-group-item">
                <div class="row">
                    <div class="col-sm-8">
                        {{ payment.created_on|datetime }}<br>
                        {{ payment.description }}<br>
                        {% trans %}Identifier{% endtrans %}: {{ payment.payment_identifier }}
                    </div>
                    <div class="col-sm-4 text-right">
                        <strong>{{ payment.amount|money }}</strong>
                    </div>
                    <div class="col-xs-1 text-center">
                        {% if not (payment.order.is_complete() or payment.order.is_canceled()) %}
                        <a
                            href="{{ url('shuup_admin:order.delete-payment', pk=payment.order_id) }}"
                            data-payment="{{ payment.pk }}"
                            name="delete-payment-link"
                            class="btn btn-danger btn-sm"
                        >
                            <i class="fa fa-close"></i>
                        </a>
                        {% endif %}
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
{% if not payments %}
    <div id="no-payments-text">
        <p>{% trans %}No payments have been created yet.{% endtrans %}</p>
    </div>
{% endif %}

Project 7 - E-Commerce Platform/shuup/admin/templates/shuup/admin/orders/_order_status_history.jinja
<div class="d-sm-none d-md-block table-responsive">
    <table class="table table-striped {% if not order_status_history %} hidden {% endif %}">
        <thead>
        <tr>
            <th>{% trans %}When{% endtrans %}</th>
            <th>{% trans %}User{% endtrans %}</th>
            <th>{% trans %}Status{% endtrans %}</th>
            <th>{% trans %}Description{% endtrans %}</th>
        </tr>
        </thead>
        <tbody>
        {% for status_history_item in order_status_history %}
            <tr>
                <td>{{ status_history_item.created_on|datetime }}</td>
                <td>{{ status_history_item.creator if status_history_item.creator else "-" }}</td>
                <td>{{ status_history_item.next_order_status }}</td>
                <td>{{ status_history_item.description if status_history_item.description else '-' }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="d-none d-sm-block d-md-none mobile-list-group {% if not order_status_history %} hidden {% endif %}">
    <ul class="list-group">
        {% for status_history_item in order_status_history %}
            <li class="list-group-item">
                <div class="row">
                    <div class="col-sm-8">
                        {{ status_history_item.created_on|datetime }}<br>
                        {{ status_history_item.creator if status_history_item.creator else "-" }}<br>
                        {% trans %}Description{% endtrans %}: {{ status_history_item.description if status_history_item.description else '-' }}
                    </div>
                    <div class="col-sm-4 text-right">
                        <strong>{{ status_history_item.next_order_status }}</strong>
                    </div>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>
{% if not order_status_history %}
    <div id="no-order-status-history-text">
        <p>{% trans %}The order has no status history.{% endtrans %}</p>
    </div>
{% endif %}

Project 7 - E-Commerce Platform/shuup/admin/templates/shuup/admin/orders/create.jinja
{% extends "shuup/admin/base.jinja" %}
{% from "shuup/admin/macros/general.jinja" import content_block, text_between_fields %}

{% block body_class %}order-create{% endblock %}

{% block content %}
    <div id="order-tool-container"></div>
{% endblock %}

{% block extra_js %}
    <script src="{{ shuup_static("shuup_admin/js/order-creator.js") }}"></script>
    <script>window.OrderCreator.init({{ config|json }})</script>
{% endblock %}

Project 7 - E-Commerce Platform/shuup/admin/templates/shuup/admin/orders/create_full_refund.jinja
{% extends "shuup/admin/base.jinja" %}
{% from "shuup/admin/macros/general.jinja" import content_block %}

{% block content %}
    <div class="container-fluid">
        <div class="content-block">
            {% include "shuup/admin/orders/_refund_order_contents.jinja" with context %}
            <form method="post" id="create_refund">
                {% csrf_token %}
                <div class="text-right">
                    <h3>{% trans %}Refund Amount{% endtrans %}: {{ order.get_total_unrefunded_amount()|money }}</h3>
                </div>
                {{ bs3.form(form) }}
                <div class="content">
                    <p><i class="fa fa-warning text-warning"></i> {% trans %}Are you sure you want to create a full refund?{% endtrans %}</p>
                    <button id="create-full-refund" class="btn btn-info">{% trans %}Confirm Refund{% endtrans %}</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

Project 7 - E-Commerce Platform/shuup/admin/templates/shuup/admin/orders/create_payment.jinja
{% extends "shuup/admin/base.jinja" %}
{% from "shuup/admin/macros/general.jinja" import content_block %}
{% block content %}
    <div class="container-fluid">
        {% call content_block(_("Order Contents"), "fa-file-text") %}
            <form method="post" id="create_payment">
                {% csrf_token %}
                {% include "shuup/admin/orders/_order_contents.jinja" with context %}
                <div class="row p-3 create-payment">
                    <div class="col-lg">
                        {{ bs3.field(form.amount) }}
                        <button id="total-unpaid" class="btn btn-primary ml-2" value="{{ order.get_total_unpaid_amount().value }}" type="button">Get Remaining Total</button>
                    </div>
                    <div class="col-lg create-payment-total text-right p-2 pr-1">
                        <h5>{% trans %}Paid{% endtrans %}</h5>
                        <h2>{{ order.get_total_paid_amount()|money }}</h2>
                        <h5>{% trans %}Remaining{% endtrans %} </h5>
                        <h2>{{ order.get_total_unpaid_amount()|money }}</h2>
                    </div>
                </div>
            </form>
        {% endcall %}
    </div>
{% endblock %}
{% block extra_js %}
    <script>
        $("#total-unpaid").click(function(event) {
            event.preventDefault();
            var total = parseFloat($(this).val());
            $("#id_amount").val(total.toFixed(2));
        })
    </script>
{% endblock %}